server:
  username: "unbound"
  directory: "/etc/unbound"
  root-hints: "/var/lib/unbound/root.hints"

  interface: 127.0.0.1
  port: 53
  do-ip4: yes
  do-ip6: yes
  do-udp: yes
  do-tcp: yes

  # Security and robustness
  harden-glue: yes
  harden-dnssec-stripped: yes
  qname-minimisation: no
  hide-identity: yes
  hide-version: yes
  prefetch: yes
  prefetch-key: yes
  edns-buffer-size: 1232
  cache-min-ttl: 0
  cache-max-ttl: 86400

  # Allow only local access
  access-control: 127.0.0.0/8 allow

