# Hardening for Apache + SSL (Lego-Certificates)
SSLProtocol             all -SSLv3 -TLSv1 -TLSv1.1
SSLCipherSuite          HIGH:!aNULL:!MD5:!3DES:!CAMELLIA:!SHA1
SSLHonorCipherOrder     on
SSLCompression          off

# Diffie-Hellman parameters
SSLOpenSSLConfCmd       DHParameters "{{.DHParamsPath}}"

# Security headers
Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
Header always set X-Content-Type-Options "nosniff"
Header always set X-Frame-Options "SAMEORIGIN"
Header always set X-XSS-Protection "1; mode=block"

