enabled = true;
use_domain = "header";
sign_authenticated = true;
try_fallback = false;
allow_hdrfrom_mismatch = false;
allow_username_mismatch = false;

domain {
{{- range .DKIMs}}
{{.}}
{{- end}}
}

