services:
  maintenance:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME}
    user: "${GDTOOLS_UID}:${DOCKER_GID}"
    restart: always
    volumes:
      - "{{ .DataDir }}:/usr/share/nginx/html:ro"
    ports:
      - "{{ .ServicePort }}:80"
    networks:
      - default

