auth_mechanisms = plain login

sql_driver = mysql

mysql /run/mysqld/mysqld.sock {
  user = vmail
  password = {{.Password}}
  dbname = vmail
}

passdb_default_password_scheme = BLF-CRYPT

passdb sql {
  query = \
    SELECT email AS user, \
           COALESCE(user_password, initial_password) AS password \
    FROM virtual_users \
    WHERE email = '%{user}'
}

userdb static {
  fields {
    uid = vmail
    gid = vmail
    home = {{.Mailer.MailPath}}/%{user | domain}/%{user | username}
  }
}

