mail_driver = maildir
mail_home = {{.Mailer.MailPath}}/%{user | domain}/%{user | username}
mail_path = ~/Maildir

maildir_stat_dirs = yes
mail_privileged_group = vmail
mailbox_list_utf8 = yes

first_valid_uid = 100
last_valid_uid = 200

namespace inbox {
   separator = /
   inbox = yes
}

