protocol imap {
  mail_plugins {
    last_login = yes
  }
}

last_login {
  dict proxy {
    name = sql
  }
  key = last-login/%{service}/%{user}/%{remote_ip}
  precision = ms
}

dict_server {
  dict sql {
    sql_driver = mysql
    mysql localhost {
      dbname = vmail
      user = vmail
      password = {{.Password}}
    }

    dict_map shared/last-login/$service/$user/$remote_ip {
      sql_table = last_login

      value_field last_access {
        type = uint
      }

      key_field email {
        value = $user
      }
      key_field service {
        value = $service
      }
      key_field last_ip {
        value = $remote_ip
      }
    }
  }
}

