protocols {
  lmtp = yes
}

protocol lmtp {
  mail_plugins {
    sieve = yes
  }
}

service lmtp {
  inet_listener lmtp {
    listen = 127.0.0.1
    port = 2424
  }

  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0600
    user = postfix
    group = postfix
  }
}

sieve_script before_scripts {
  type = before
  driver = file
  path = {{.SieveBefore}}
}

sieve_script after_scripts {
  type = after
  driver = file
  path = {{.SieveAfter}}
}

