; Set timezone
date.timezone = {{.TimeZone}}

; Enable APCu
apc.enable_cli = 1

; Memory and upload limits
upload_max_filesize = 2G
post_max_size = 2G
memory_limit = 512M
max_execution_time = 300
max_input_time = 300

; Opcache tuning
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 32

