Syslog                  yes
SyslogSuccess           yes
LogWhy                  yes

UMask                   002
UserID			opendkim

Mode                    sv
Canonicalization        relaxed/simple
SubDomains              no
OversignHeaders		From

SignatureAlgorithm      rsa-sha256

Socket                  inet:{{.OpenDKIMPort}}@localhost
PidFile                 /run/opendkim/opendkim.pid

KeyTable                /etc/opendkim/KeyTable
SigningTable            refile:/etc/opendkim/SigningTable
InternalHosts           /etc/opendkim/TrustedHosts

TrustAnchorFile		/usr/share/dns/root.key

